- name: Branding
  keywords: Original. Smart. Memorable.
  description: "Launching or re-establishing a business or new brand is an ambitious undertaking. Maximize your position with the experience and talent of the Insight staff at your side. Contact Insight to set yourself above your competitors with an exclusive brand identity and personality that resonates with your customers."
  tags:
  - Positioning
  - Naming
  - Slogans
  - Tag Lines
  - Logo Development
  - Letterhead design
  example1:
  example2:
  example3:

- name: Copywriting
  keywords: Savvy. Descriptive. Concise.
  description: "It’s all in the way you say it… and Insight says it best with persuasive and compelling concepts and copy for all your marketing communications. Creating memorable headlines, targeted messages and effective ad and collateral material copy takes expertise, skill and careful study of your goals and market position. Insight has the experienced staff to excel at all your writing projects and generate impressive results."
  tags:
  - Creative
  - Concepting
  - Ad Copy
  - Radio Scripting
  - Television Scripting
  - Media Releases
  - Brochures
  - Newsletters
  - Articles
  - Names
  - Slogans
  - Catch Phrases
  - Billboards
  - Technical Writing
  - Presentations
  example1:
  example2:
  example3:

- name: Graphic Design
  keywords: Unique. Bold. Sophisticated.
  description: "Our designs catch attention, reflect your brand personality and enhance the messages you need to communicate to your audience. Insight’s team of graphic designers brings years of experience, talent and a critical eye to each project. See what an impact professional design can have on your materials!"
  tags:
  - Creative Concepting
  - Brochures
  - Newsletters
  - Direct Mail
  - Catalogs
  - Menus
  - Newspaper Ads
  - Billboards
  - Outdoor Media
  - Annual Reports
  - Sell Sheets
  - Packaging
  - Point of Purchase
  - Trade Publication Ads
  - Trade Show Displays
  - Websites
  - Interactive Materials
  example1:
  example2:
  example3:

- name: Media Buying
  keywords: Radio! Online! TV! Billboards! Newspapers!
  description: "You have so many choices when it comes to where to put your marketing resources. With our expertise and knowledge of emerging platforms, Insight can design a plan just for your business, to reach your targeted customer base and make multiple, lasting impressions. We make a study of media, using careful research, professional software and a variety of media sources to craft a strategy and plan uniquely effective for you. Our respected media planners and buyers have diverse backgrounds and experience in broadcast, interactive, social media and more. They have the knowledge, inside information and skill needed to negotiate the best value for our clients. And the service doesn’t stop with the buy. We place each spot we purchase - ensuring the best timing to reach your largest audience. Our media specialists’ in-depth understanding of smart media planning will make your dollars work harder. We’re also able to leverage our position as a major media buyer to negotiate the best rates and positions for your messages!"
  tags:
  - Media neutral planning, placement and analysis
  - Nielsen Ratings (TV and Radio)
  example1:
  example2:
  example3:

- name: Photography
  keywords: Brilliant. Stylistic. Edgy.
  description: "True photographic expertise showcases your products, business and people in the best light. Rely on our experience with industrial products, food, architecture and everything in-between. Our in-house photographers and complete photo studio are key attributes that set Insight above other agencies."
  tags:
  - Multiple on-staff Stylists, Designers & Photographers
  - In-house Studio
  - On-location Capabilities
  - Digital & Traditional Photographic Options
  - Digital Retouching Services
  - Versatile Backgrounds
  - Prop Sourcing
  example1:
  example2:
  example3:

- name: Public Relations
  keywords: Sharp. Reputable. Persistent.
  description: "Although the tools are constantly evolving, we believe the fundamentals of good public relations remain the same; Insight can help you strengthen relationships, share your message and create a greater impact for the people who matter most to your organization. Whether you want to build or repair your image, plan and promote a special event or learn to communicate effectively with your target audience, we have the experience and creativity to help you reach your goals."
  tags:
  example1:
  example2:
  example3:

- name: Social Media
  keywords: Strategic. Conversational. Engaging.
  description: "The social media landscape is changing at a rapid pace. Let us keep up with the latest advancements; we’ll work with you to determine the strategies, tactics and trends that will best attract and engage your customers. We’ll outline measurable objectives and integrate a strong social media program with your traditional marketing efforts."
  tags:
  - Strategy Development
  - Platform Set-Up or Optimization
  - Content Creation
  - Community Monitoring and Response
  - Social Media Advertising
  - Analytics & Reporting
  example1:
  example2:
  example3:

- name: Video/Audio
  keywords: Professional. Memorable. Artistic.
  description: "Our professional video production skills bring quality production values to your commercials, corporate videos or event presentations. Our complete in-house video and audio studios and equipment mean quick turnaround times and an efficient use of your budget with impressive results."
  tags:
  - Concept Development
  - Script Writing
  - Storyboarding
  - On-Location & Studio Shooting Capabilities
  - Video Editing
  - Audio Recording & Production
  - Post-Production Detailing
  example1:
  example2:
  example3:

- name: Web Design & Dev.
  keywords: Intriguing. Animated. Integrated.
  description: "Our interactive development capabilities bring you quickly to the forefront of current marketing practices. Websites designed by Insight load quickly, are user-friendly, and bring a contemporary look and feel to your online presence."
  tags:
  - Website Development
  - Hosting
  - Graphics
  - Animation
  - Banners
  - Links
  - Maintenance
  - Email Marketing
  - Online Research & Surveying
  example1:
  example2:
  example3:
